### ISSUE TITLE
fix for gitlab 13.9.4

### ISSUE THREAD

**Issue by agdula** [tomasbjerre/jenkins-configuration-as-code-sandbox#2]
Hi,

This is a great project. Thanks for sharing!

The most recent version of gitlab is not compatible with create-personal-access-token.sh. 
I've made a PR for a python version of the script 

https://github.com/vitalyisaev2/gitlab_token/pull/1/commits/f00ab87bbce7207840dfe4b1a111a52204dba0da

You could apply the changes to the script yourself... or maybe consider using approach from this fork
https://github.com/agdula/jenkins-configuration-as-code-sandbox/commit/f8051dbe686a63e78566b7cac0b0784e32857005

**Comment by tomasbjerre** [comment]
Thanks!

I applied both changes and pushed to this repo now.

**Comment by agdula** [comment]
Yeah... so

I might've created this issue in a little confusing way. My intention was
to let you know, that the personal_access_token logic needed attention.
The change I've made on my clone of you repo was did not need the first
change as that was supposed to be an 'example' of what needed to be done.

Anyways, I see that you've integrated the changes from my fork. There is 1
thing that has to be fixed and one that would be improvement.
1. the access token is not "propagated" to the jenkins instance as a
consequence of the setup script running in a separate container
2. the setup container could wait for the gitlab to be up and running and
the start the initial setup

I'll try to do something about that. Thanks!


niedz., 21 mar 2021 o 09:01 Tomas Bjerre ***@***.***>
napisał(a):

**Comment by tomasbjerre** [comment]
Ok!

I reverted the code in this repo.

It would be great if you can supply a pull request with a proper fix.

**Comment by tomasbjerre** [comment]
Fixed in https://github.com/tomasbjerre/jenkins-configuration-as-code-sandbox/pull/3
