### ISSUE TITLE
Error OCI runtime failed jenkins-wrapper.sh cannot exectute

### ISSUE THREAD

**Issue by RickBankers** [tomasbjerre/jenkins-configuration-as-code-sandbox#4]
When I run the docker compose I am getting an error about being unable to execute jenkins-wrapper.sh. If I make this file executable I get other errors:
ERROR: for jenkins-configuration-as-code-sandbox_gitlab-setup_1  Cannot start service gitlab-setup: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/bootstrap/main.sh\": permission denied": unknown

ERROR: for gitlab-setup  Cannot start service gitlab-setup: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/bootstrap/main.sh\": permission denied": unknown

**Comment by bguerin** [comment]
See pull request #5

**Comment by tomasbjerre** [comment]
Thanks
