### ISSUE TITLE
Token Credential Question

### ISSUE THREAD

**Issue by wg21908** [tomasbjerre/jenkins-configuration-as-code-sandbox#6]
I have been successful at installing your plugin in Jenkins and configuring a freestyle job that uses the plugin so that I can reference variables and headers sent from the GitHub JSON based payload.

The Jenkins job that is working right now is configured with a regular hard-coded token, not the Jenkins credential based token option that you provide.  I have been trying to migrate away from the hard-coded token to the credential based token without success.  In Jenkins I successfully create a user/password based credential without problem but that new Jenkins credential does not display as an option in the “Token Credential” drop down.

Any advice on what I might be doing wrong?

**Comment by tomasbjerre** [comment]
The credential should be of type "secret text".
